name: pyvolution
channels:
  - defaults
dependencies:
  - certifi=2018.4.16
  - icc_rt=2017.0.4
  - intel-openmp=2018.0.0
  - m2-base=1.0.0
  - m2-bash=4.3.042
  - m2-bash-completion=2.3
  - m2-catgets=1.1
  - m2-coreutils=8.25
  - m2-dash=0.5.8
  - m2-file=5.25
  - m2-filesystem=2016.04
  - m2-findutils=4.6.0
  - m2-gawk=4.1.3
  - m2-gcc-libs=5.3.0
  - m2-gettext=0.19.7
  - m2-gmp=6.1.0
  - m2-grep=2.22
  - m2-gzip=1.7
  - m2-inetutils=1.9.2
  - m2-info=6.0
  - m2-less=481
  - m2-libasprintf=0.19.7
  - m2-libcatgets=1.1
  - m2-libcrypt=1.3
  - m2-libgettextpo=0.19.7
  - m2-libiconv=1.14
  - m2-libintl=0.19.7
  - m2-liblzma=5.2.2
  - m2-libpcre=8.38
  - m2-libreadline=6.3.008
  - m2-libutil-linux=2.26.2
  - m2-libxml2=2.9.2
  - m2-mintty=1!2.2.3
  - m2-mpfr=3.1.4
  - m2-msys2-launcher-git=0.3.28.860c495
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-ncurses=6.0.20160220
  - m2-sed=4.2.2
  - m2-tftp-hpa=5.2
  - m2-time=1.7
  - m2-ttyrec=1.0.8
  - m2-tzcode=2015.e
  - m2-util-linux=2.26.2
  - m2-which=2.21
  - m2-zlib=1.2.8
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - msys2-conda-epoch
  - numpy=1.13.3
  - pip=10.0.1=py36_0
  - python=3.6.5
  - setuptools=39.1.0
  - vc=14
  - vs2015_runtime=14.0.25123
  - wheel=0.31.0
  - wincertstore=0.2
